CFLAGS += 
LIBS += 

PREFIX = $(DESTDIR)/usr/local
PACKAGEDIR = $(PREFIX)/share/$(PACKAGE)-$(VERSION)
TRUEPACKAGEDIR = /usr/local/share/$(PACKAGE)-$(VERSION)
SBINDIR = $(PREFIX)/sbin
SYSCONFDIR = $(PACKAGEDIR)/etc

OBJECTS = main.o init.o socket.o request.o status.o config.o globals.o strndup.o clearenv.o type.o handler.o log.o
