CFLAGS += 
LIBS += 

PREFIX ?= $(DESTDIR)/usr/local
PACKAGEDIR ?= $(PREFIX)/share/$(PACKAGE)-$(VERSION)
TRUEPREFIX ?= /usr/local
TRUEPACKAGEDIR ?= $(TRUEPREFIX)/share/$(PACKAGE)-$(VERSION)
LOGDIR ?= $(DESTDIR)/var/log
SBINDIR ?= $(PREFIX)/sbin
SYSCONFDIR ?= $(DESTDIR)/etc
MANDIR ?= $(PREFIX)/share/man

OBJECTS = main.o init.o socket.o request.o status.o config.o globals.o strndup.o clearenv.o type.o handler.o log.o
