CFLAGS ?= 
LIBS +=  -lssl -lcrypto

VERSION = 1.1.1

PREFIX ?= $(DESTDIR)/usr/local
PACKAGEDIR ?= $(PREFIX)/share/$(PACKAGE)-$(VERSION)
TRUEPREFIX ?= /usr/local
TRUEPACKAGEDIR ?= $(TRUEPREFIX)/share/$(PACKAGE)-$(VERSION)
SBINDIR ?= $(PREFIX)/sbin
SYSCONFDIR ?= $(DESTDIR)/etc
MANDIR ?= $(PREFIX)/man
LOGDIR ?= $(DESTDIR)/var/log

OBJECTS = main.o globals.o init.o socket.o request.o status.o config.o serve.o strndup.o clearenv.o handler.o log.o type.o ssl.o
